name: Build, Test, and Deploy on Develop
  
on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Verify build directory contents
        run: |
          ls -l dist/apps/catalog

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/apps/catalog

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/apps/catalog

      - name: Run tests
        run: npm test
        

      - name: Start application
        run: npm start &
        env:
          CI: true

      - name: Run Cypress tests
        run: npm run test:cypress

      - name: Run Lighthouse performance tests
        run: |
          npm install -g lighthouse
          lighthouse http://localhost:3000 --output=json --output-path=./lighthouse-report.json

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/reports/

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: ./lighthouse-report.json
        
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/apps/catalog

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/apps/catalog s3://${{ secrets.S3_ORIGIN_BUCKET_DEV }} --delete