name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
      - Staging

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Terraform Repository
        run: git clone --branch main https://github.com/Proyecto-DevOps-Gonzalo-Gaston/DevOps terraform

      - name: Verify Cloned Directory
        run: |
          ls -l terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/Terraform/TerraformFE
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/Terraform/TerraformFE
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform/Terraform/TerraformFE
          terraform apply -auto-approve || exit 0

      - name: Terraform Apply 2
        run: |
          cd terraform/Terraform/TerraformFE
          terraform apply -auto-approve