name: Github Action Workflow STAGE

on:
  push:
    branches:
      - Staging
  repository_dispatch:
    types:
      - build-stage
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dev:
    uses: Proyecto-DevOps-Gonzalo-Gaston/DevOps/.github/workflows/deploy-to-s3.yml@Staging
    with:
      CI_ENV: Staging
      CONTENTFUL_ENVIRONMENT: 'Staging'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_STG }}
